
placards:
	pandoc -s -V fontsize=10pt --template=default.latex -V papersize:a5   atari.md -o atari.pdf
	pandoc -s -V fontsize=10pt --template=default.latex -V papersize:a5   bebox.md -o bebox.pdf
	pandoc -s -V fontsize=10pt --template=default.latex -V papersize:a5   c64.md -o 664.pdf
	pandoc -s -V fontsize=10pt --template=default.latex -V papersize:a5   cpc6128.md -o cpc6128.pdf
	pandoc -s -V fontsize=10pt --template=default.latex -V papersize:a5   macintosh.md -o macintosh.pdf
	pandoc -s -V fontsize=10pt --template=default.latex -V papersize:a5   olivetti.md -o olivetti.pdf
	pandoc -s -V fontsize=10pt --template=default.latex -V papersize:a5   oric.md -o oric.pdf
	pandoc -s -V fontsize=10pt --template=default.latex -V papersize:a5   sgi.md -o sgi.pdf
	pandoc -s -V fontsize=10pt --template=default.latex -V papersize:a5   zxspectrum.md -o zxspectrum.md.pdf
